### PR TITLE
Prevent for broke touchscreen after resume

### PR DESCRIPTION
**Pull request by petrmatula190**
Sometimes after resume from suspend, touchscreen not working and in dmesg is lot of messanges with goodix touch driver and i2c (touchscreen is connected over i2c bus). I try fix it and found this easy solution.
[dmesg output after error happend](https://raw.githubusercontent.com/petrmatula190/gpd-pocket-ubuntu-respin/master/Touchscreen_resume_errors.png)

Before sleep, driver must be remove and after resume reload back.

### CODE REVIEW

**Comment by petrmatula190** [comment]
I tried create wrapper for build ISO image, but it is not working. @stockmind, If you know how to make working, please do it. Thanks.

**Comment by stockmind** [comment]
Checked the code just now and it seems fine, what wasn't working? The file didn't got copied?

**Comment by petrmatula190** [comment]
No, File is copied in ISO, but nothing found after install in virtualbox. But script for copy in update.sh working perfectly.

EDIT:
In build.sh, this lines must be OK. 
	-f touch/goodix-sleep.service \\
 	-f touch/goodix-resume.service \\
 	-f touch/wrapper-touchscreen.sh \\
 	-c wrapper-touchscreen.sh \

wrapper-touchscreen.sh shouls be OK too.
This three files were copied in ISO in folder /usr/local/bin, but missing after instalation.

**Comment by petrmatula190** [comment]
@jwrdegoede commited fix for goodix touch driver, but I want need about week for long-time testing.  https://github.com/jwrdegoede/linux-sunxi/commit/1f5c4f2c220c53e80dfaaa5fcf20ae6743c04b43


So, my pull request is outdated. 

There is my compiled kernel with this commit and used .config from your repo + working audio (need copy HiFi.conf).
https://drive.google.com/file/d/1Bxdmyk4TnQbnty3AKtUuwrOUAnotNgwP/view?usp=drivesdk

**Comment by stockmind** [comment]
Thank Petr for all your work! The system was never so complete! :) I close this as is now resolved

**Pull request closed without merging**
